############## style ##############
style:
  layout:
    max-width: 1130px #总体宽度
    post-max-width: 800px #文章内容宽度
  color:
    theme-main: "#1A98FF" # 主色调
    theme-secondary: "#DDF0FF" # 次色调
    text-main: "#333333" # 文字主色调
    text-secondary: "#898FA0" # 文字次色调
  animation:
    open: true # 如果开启动画的话会引入animation.css


########## 关于主页的设置 ##########
# home页可选类型
home:
  type: "home" # 主页的类型，可选 home | img | simple

# archive页可选类型
archive:
  type: "simple" # archive的类型，可选 img | simple

categories:
  type: "img" # archive的类型，可选 img | simple

tags:
  type: "img" # archive的类型，可选 img | simple

archive_img_mode:
  default_cover: #默认的cover
    - /image/img/1.jpg
    - /image/img/2.jpg
    - /image/img/3.jpg
    - /image/img/4.jpg
    - /image/img/5.jpg
    - /image/img/6.jpg.
    - /image/img/7.jpg
    - /image/img/8.jpg
    - /image/head.jpg
    - /image/head1.jpg
# icon
icon: /image/favicon.ico #标签页图标
#  header
site_name: Luyancib
site_description: 这里会存放一些东西 #The default meta description for all the meta descriptions
#Add description property to any page to change the meta description
menu:
  首页: /
  归档: /p
  #战队: /tnj
  #下载: /dl
  #其他: /ov
  #en: https://luyanei-en.vercel.app
  #Github Pages: https://luyanci.github.io

## 本地搜索
search:
  open: true # 是否开启
  page: /search # 页面路径（通常命名为search）



# 自我介绍
intro:
  title: YC的博客网站
  sub: '这里会存放一些东西，[点击这里](/p)来查看内容！' # markdown语法
  avator: https://cdn.jsdelivr.net/gh/fushaolei/img/20200524104925.jpg #头像 暂时还没用到
  author: luyanci #所有文章的默认作者

#联系方式
#更多图标：https://remixicon.com/
contact:
  home:
    - /
    - ri-home-4-line
  find:
    - /search
    - ri-search-line
  github:
    - https://github.com/luyanci
    - ri-github-fill
  Gitee:
    - https://gitee.com/luyanei
    - ri-github-line
  bilibili:
    - https://space.bilibili.com/282873551
    - ri-bilibili-line
  qq:
    - http://qm.qq.com/cgi-bin/qm/qr?_wv=1027&k=ooQLGgF47KvSMkS6nHGLWIGzDFntJ3U3&authKey=kln3N0C6qP4OPlCmDntPFBxF10uICUr7tEH%2BnQ1yySz5oMchzjZhAvkvJ9FVgl8w&noverify=0&group_code=738434011
    - ri-qq-line
  Email:
    - mailto:luyanxi2007@qq.com
    - ri-mail-line
    

########## 关于文章的设置 ##########

# 文章toc索引栏设置
toc:
  open: true # 是否开启
  side: true  # 选择toc的位置，填true的话toc将会显示在文章的侧边，填false的话 toc将出现在文章的开头
  max: 2 #最大深度
  min: 2 #最小深度

# 插件
plugins:
  # 代码高亮，想要使用代码高亮，得先把根目录的_config.yml里的highlight的enable置成false
  highlightjs:
    js: https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@9.18.1/build/highlight.min.js
    css: https://cdn.jsdelivr.net/npm/highlight.js@10.1.1/styles/github.css
    # more: https://www.jsdelivr.com/package/npm/highlight.js?path=styles

# 评论系统设置
comments:
  open: true #是否开启评论系统
  system: livere #选择评论系统 可选 valine gitalk livere
  # Valine
  valine:
    appid: #Leancloud应用的AppID  这里和下面的要换成你自己的啊QAQ
    appkey: #Leancloud应用的AppKey
    verify: false #验证码
    notify: true #评论回复提醒
    avatar: robohash #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
    #头像类型可见： https://valine.js.org/avatar.html
    placeholder: 留下你来过的痕迹~ #评论框占位符
  # Gitalk
  gitalk:
    owner: 'luyanci' #Github 用户名,
    repo: 'luyanci.github.io' #储存评论issue的github仓库名
    admin: 'luyanci' #Github 用户名
    clientID: cc90d60963ef56f3ee85 #`Github Application clientID`
    clientSecret: 936ecdcea8d74a4b8c326bdb920ccabccb3bbffe #`Github Application clientSecret`
  #livere
  livere: # 前往 http://livere.com/ 申请账号
    dataId: city #免费版本city
    dataUid: MTAyMC81NTEwNi8zMTU3NA== #安装代码中 data-uid 后面数据


pagination:
  prev: prev
  next: next

############## 其他 ##############

# 页脚
footer: 本博客为[YC酱luyancib](https://space.bilibili.com/282873551)的个人博客 # markdown语法

#有分类时是否开启menu分类页和自定义名字
menu_categories:
  open: true
  name: 分类

#可自定义归档标签页名字
archive_tab_name: 归档


#图片懒加载
lazyload:
  open: true #是否开启
